version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    container_name: prisma
    depends_on:
      - postgres-db
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres-db
            port: 5432
            user: prisma
            password: prisma
  postgres-db:
    image: postgres:10.3
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~